version: '3.9'

services:
  app:
    image: oc_lettings_project:v4
    build:
      context: .
    volumes:
      - .:/oc_lettings_project
    ports:
      - "8000:8000"
    container_name: oc_lettings_container