version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
jobs:
  build-lint-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
            name: lint
            command: flake8
      - run:
            name: run tests
            command: pytest

workflows:
  heroku_deploy:
    jobs:
      - build-lint-test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build-lint-test
