version: 2.1

orbs:
  python: circleci/python@2.0.3
jobs:
  build:
    docker:
      - image: antakathena/oc-lettings-5:latest
        auth:
          username: antakathena
          password: DOCKERHUB_PASSWORD
  lint-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
            name: lint
            command: flake8
      - run:
            name: run tests
            command: pytest

workflows:
  version: 2
  prepare:
    jobs:
      - build-lint-test:
          filters:
            branches:
              only:
                - master
      #        ignore: /.*/



#
#orbs:
#  python: circleci/python@2.0.3
# jobs:
#   build-lint-test:
#    docker:
#      - image: cimg/python:3.10.4
#    # By default it uses the project root's requirements.txt.
#     CircleCI will report the results back to your Version Control System (VCS) provider.
#    steps:
#      - checkout
##  - python/install-packages:
##  pkg-manager: pip
#      - run:
#            name: install dependencies
#            command: pip install -r requirements.txt
#      - run:
#            name: lint
#            command: flake8
#      - run:
#            name: run tests
#            command: pytest
#
#workflows:
#  version: 2
#  prepare:
#    jobs:
#      - build-lint-test:
#          filters:
#            branches:
#              only:
#                - master
#      #        ignore: /.*/