version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6

executors:
 docker-publisher:
   docker: # Each job requires specifying an executor
   # (either docker, macos, or machine), see
    - image: cimg/node:12.16
      docker_layer_caching: true
   # vérifier le tag SHA des variables de circleci
      auth:
       username: $DOCKERHUB_USERNAME
       password: $DOCKERHUB_PASSWORD

jobs:
  build-lint-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
            name: lint
            command: flake8
      - run:
            name: run tests
            command: pytest

  publish-latest-to-DockerHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_SHA1
            
  heroku-deploy:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Pull and tag image from Dockerhub
          command: |
            docker pull $IMAGE_NAME:$CIRCLE_SHA1
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 antakathena/$HEROKU_APP_NAME/web
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=$HEROKU_API_KEY heroku container:login
            HEROKU_API_KEY=$HEROKU_API_KEY docker push -a antakathena/$HEROKU_APP_NAME/web
            HEROKU_API_KEY=$HEROKU_API_KEY heroku container:release web

workflows:
  heroku_deploy:
    jobs:
      - build-lint-test
      - publish-latest-to-DockerHub:
          requires:
            - build-lint-test
      - heroku-deploy:
          requires:
            - publish-latest-to-DockerHub

