version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.6

executors:
 docker-publisher:
   docker: # Each job requires specifying an executor
   # (either docker, macos, or machine), see
    - image: cimg/node:12.16
   # vérifier le tag SHA des variables de circleci
      auth:
       username: $DOCKERHUB_USERNAME
       password: $DOCKERHUB_PASSWORD

jobs:
  build-lint-test:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
            name: lint
            command: flake8
      - run:
            name: run tests
            command: pytest

  publish-latest-to-DockerHub:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_SHA1

  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - build-lint-test
      - publish-latest-to-DockerHub:
          requires:
            - build-lint-test
      - deploy:
          requires:
            - publish-latest-to-DockerHub

